{% set version = "1.7.8" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-lubridate
  version: {{ version|replace("-", "_") }}

source:
  fn: lubridate_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/lubridate_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/lubridate/lubridate_{{ version }}.tar.gz
  sha256: 3da19922fc373e113ecc58c4984955ba26da703edc9c991bd444b7077d4b553c

build:
  merge_build_host: true  # [win]
  number: 0
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('m2w64_cxx') }}        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-rcpp >=0.12.13
    - r-stringr
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-rcpp >=0.12.13
    - r-stringr

test:
  commands:
    - $R -e "library('lubridate')"           # [not win]
    - "\"%R%\" -e \"library('lubridate')\""  # [win]

about:
  home: http://lubridate.tidyverse.org, https://github.com/tidyverse/lubridate
  license: GPL (>= 2)
  summary: "Functions to work with date-times and time-spans: fast and user friendly parsing of date-time data, extraction and updating of components of a date-time\
    \ (years, months, days, hours, minutes, and seconds), algebraic manipulation on date-time and time-span objects. The 'lubridate' package has a consistent and\
    \ memorable syntax that makes working with dates easy and fun. Parts of the 'CCTZ' source code, released under the Apache 2.0 License, are included in this package.\
    \ See <https://github.com/google/cctz> for more details."
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
