{% set version = "1.9.4" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-lubridate
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/lubridate_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/lubridate/lubridate_{{ version }}.tar.gz
  sha256: 864b7ee223d622d41214c6aacc7d68d8984090a8e1e823c729983d33624646c1

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-generics                   # [build_platform != target_platform]
    - r-timechange                 # [build_platform != target_platform]
  host:
    - r-base
    - r-generics
    - r-timechange >=0.1.1
  run:
    - r-base
    - r-generics
    - r-timechange >=0.1.1

test:
  commands:
    - $R -e "library('lubridate')"           # [not win]
    - "\"%R%\" -e \"library('lubridate')\""  # [win]

about:
  home: https://lubridate.tidyverse.org
  dev_url: https://github.com/tidyverse/lubridate
  doc_url: https://lubridate.tidyverse.org/reference/
  license: GPL-2.0-or-later
  summary: 'Functions to work with date-times and time-spans: fast and user friendly parsing of date-time data, extraction and updating of components of a date-time (years, months, days, hours, minutes, and seconds), algebraic manipulation on date-time and time-span objects. The ''lubridate'' package has a consistent and
    memorable syntax that makes working with dates easy and fun.'
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
