{% set version = "1.9.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-lubridate
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/lubridate_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/lubridate/lubridate_{{ version }}.tar.gz
  sha256: 8976431a4affe989261cbaa5e09cd44bb42a3b16eed59a42c1698da34c6544a7

build:
  merge_build_host: true  # [win]
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-generics                   # [build_platform != target_platform]
    - r-timechange                 # [build_platform != target_platform]
  host:
    - r-base
    - r-generics
    - r-timechange >=0.1.1
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-generics
    - r-timechange >=0.1.1

test:
  commands:
    - $R -e "library('lubridate')"           # [not win]
    - "\"%R%\" -e \"library('lubridate')\""  # [win]

about:
  home: https://lubridate.tidyverse.org
  dev_url: https://github.com/tidyverse/lubridate
  doc_url: https://lubridate.tidyverse.org/reference/
  license: GPL-2.0-or-later
  summary: 'Functions to work with date-times and time-spans: fast and user friendly parsing
    of date-time data, extraction and updating of components of a date-time (years,
    months, days, hours, minutes, and seconds), algebraic manipulation on date-time
    and time-span objects. The ''lubridate'' package has a consistent and memorable
    syntax that makes working with dates easy and fun.'
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
