appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  linux_aarch64: default
  linux_ppc64le: azure
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: emq4GgerLP6mp/FzbVKPpDZwnRXLeTLBdfmjKMU87yYxEgrgIu49toaI6xQPhl93tSWbZYhgPdP+0tjYCKrYIitNW1ucaoVv/8zf/X0yFC7AQty6Ut++NcdtuGu2zO+io7KRrnRusQayKNXPEwkIAtiMXat4P2++OTrq9EDh3jTpqgCvn0l3W7uu9Vxm3D6Cl5Cdj0muaTN+AVob1FEUf9rbtNxL0IO/fkfS4WMjuT6V6k8AVYiIT/8tsBiMa+4DIZcrcExoXa6vvgRhtK/kVkCGty+EmdW/UOXzPYT3vanud7XqU7z5nV4Xg1CQYciPdfG5QJ5iCNEYq2m692hBlOLriT1YmWvA3wtiNowXK56/gVoSHcNqcR7awuIIFiFdVC9SA0xHzM2oOsmFmb8sIwKiH5PoK0Js2aCgLZtTBmZ4nl9pxnBzJ2SA6FXjyG4khRtSdnbTa8Uw8Fh5iRxo06A1hL/+Zuqd9jgkGEKxAJ+DYquv/68+HpZhs5QzB1mQhq1KbE9BQoi7gXGBlnNaUw/jLxH4vbArsr7Wz618Gq1EZnkdSErbZYRDl1RZk8HbY/r/gkY+KdVFeMqI8+p+dE8kUfF4qCU/qNza7PAAlBBetgTqRRRk9WCfP4MUBcdoqAb0v4I7S3x/ZKA2nDJPdhCLgNdDhFIL0UTj6OYMhUU=
